spring.application.name: gateway

reeled.gateway.internal-services:
  author-service.url: http://localhost:8082
  post-service.url: http://localhost:8083
  post-metrics-service.url: http://localhost:8084

spring.cloud.gateway:
  httpclient:
    connect-timeout: 10000
    response-timeout: 29s
  routes:
    - id: author_create
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors
        - Method=POST
      filters:
        - SetPath=/api/v1/authors
    - id: author_update
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors/{authorId}
        - Method=PUT
      filters:
        - SetPath=/api/v1/authors/{authorId}
    - id: author_get
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors/{authorId}
        - Method=GET
      filters:
        - SetPath=/api/v1/authors/{authorId}
    - id: author_delete
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors/{authorId}
        - Method=DELETE
      filters:
        - SetPath=/api/v1/authors/{authorId}
    - id: author_put_analytics-email-recipients
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/authors/{authorId}/analytics-email-recipients
        - Method=PUT
      filters:
        - SetPath=/api/v1/authors/{authorId}/analytics-email-recipients
    - id: author_get_analytics-email-recipients
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/authors/{authorId}/analytics-email-recipients
        - Method=GET
      filters:
        - SetPath=/api/v1/authors/{authorId}/analytics-email-recipients
    - id: post_create
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts
        - Method=POST
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts
    - id: post_update
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/{postId}
        - Method=PUT
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/{postId}
    - id: author_get
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/{postId}
        - Method=GET
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/{postId}
    - id: post_delete
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/{postId}
        - Method=DELETE
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/{postId}
    - id: posts_metrics_import
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/posts/metrics/import
        - Method=POST
      filters:
        - SetPath=/api/v1/posts/metrics/import
    - id: posts_metrics_search
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/metrics/search
        - Method=POST
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/metrics/search

# API documentation
reeled.gateway.openapi.internal-services.urls:
  - ${reeled.gateway.internal-services.author-service.url}/v3/api-docs
  - ${reeled.gateway.internal-services.post-service.url}/v3/api-docs
  - ${reeled.gateway.internal-services.post-metrics-service.url}/v3/api-docs

springdoc:
  api-docs.enabled: true
  use-fqn: true
