spring.application.name: gateway

reeled.gateway.internal-services:
  author-service.url: http://localhost:8082
  post-service.url: http://localhost:8083
  post-metrics-service.url: http://localhost:8084
  reference-service.url: http://localhost:8087

spring.cloud.gateway:
  httpclient:
    connect-timeout: 10000
    response-timeout: 29s
  routes:
    - id: author_create
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors
        - Method=POST
      filters:
        - SetPath=/api/v1/authors
    - id: author_update
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors/{authorId}
        - Method=PUT
      filters:
        - SetPath=/api/v1/authors/{authorId}
    - id: author_get
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors/{authorId}
        - Method=GET
      filters:
        - SetPath=/api/v1/authors/{authorId}
    - id: author_delete
      uri: ${reeled.gateway.internal-services.author-service.url}
      predicates:
        - Path=/authors/{authorId}
        - Method=DELETE
      filters:
        - SetPath=/api/v1/authors/{authorId}
    - id: author_analytics_email_recipients_update
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/authors/{authorId}/analytics-email-recipients
        - Method=PUT
      filters:
        - SetPath=/api/v1/authors/{authorId}/analytics-email-recipients
    - id: author_analytics_email_recipients_get
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/authors/{authorId}/analytics-email-recipients
        - Method=GET
      filters:
        - SetPath=/api/v1/authors/{authorId}/analytics-email-recipients
    - id: post_create
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts
        - Method=POST
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts
    - id: post_update
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/{postId}
        - Method=PUT
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/{postId}
    - id: post_get
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/{postId}
        - Method=GET
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/{postId}
    - id: post_delete
      uri: ${reeled.gateway.internal-services.post-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/{postId}
        - Method=DELETE
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/{postId}
    - id: post_metrics_import
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/posts/metrics/import
        - Method=POST
      filters:
        - SetPath=/api/v1/posts/metrics/import
    - id: post_metrics_search
      uri: ${reeled.gateway.internal-services.post-metrics-service.url}
      predicates:
        - Path=/authors/{authorId}/posts/metrics/search
        - Method=POST
      filters:
        - SetPath=/api/v1/authors/{authorId}/posts/metrics/search
    - id: post_category_create
      uri: ${reeled.gateway.internal-services.reference-service.url}
      predicates:
        - Path=/post-categories
        - Method=POST
      filters:
        - SetPath=/api/v1/post-categories
    - id: post_category_get
      uri: ${reeled.gateway.internal-services.reference-service.url}
      predicates:
        - Path=/post-categories/{postCategoryKey}
        - Method=GET
      filters:
        - SetPath=/api/v1/post-categories/{postCategoryKey}
    - id: post_category_get_all
      uri: ${reeled.gateway.internal-services.reference-service.url}
      predicates:
        - Path=/post-categories
        - Method=GET
      filters:
        - SetPath=/api/v1/post-categories
    - id: author_type_get_all
      uri: ${reeled.gateway.internal-services.reference-service.url}
      predicates:
        - Path=/author-types
        - Method=GET
      filters:
        - SetPath=/api/v1/author-types

# API documentation
reeled.gateway.openapi.internal-services.urls:
  - ${reeled.gateway.internal-services.author-service.url}/v3/api-docs
  - ${reeled.gateway.internal-services.post-service.url}/v3/api-docs
  - ${reeled.gateway.internal-services.post-metrics-service.url}/v3/api-docs
  - ${reeled.gateway.internal-services.reference-service.url}/v3/api-docs

springdoc:
  api-docs.enabled: true
  use-fqn: true
