plugins {
    id 'java'
    id 'org.springframework.boot' version "$springBootVersion"
}

group = artifactGroup
version = "$artifactVersion" + (isSnapshot == "Y" ? '-SNAPSHOT' : '')

java {
    sourceCompatibility = '21'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
    annotationProcessor platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")

    // web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'io.github.wimdeblauwe:error-handling-spring-boot-starter:4.5.0'

    // database
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.liquibase:liquibase-core'
    implementation 'org.postgresql:postgresql'

    // security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // commons
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
    implementation 'org.apache.commons:commons-csv:1.12.0'

    // scheduling
    implementation 'net.javacrumbs.shedlock:shedlock-spring:6.0.2'
    implementation 'net.javacrumbs.shedlock:shedlock-provider-jdbc:6.0.2'

    // testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar {
    archiveClassifier = 'boot'
    manifest {
        attributes 'Implementation-Title': artifactName,
                'Implementation-Version': archiveVersion
    }
}

springBoot {
    buildInfo()
}

test {
    useJUnitPlatform()

    maxHeapSize = '1024M'
    jvmArgs '-XX:MaxMetaspaceSize=256M'
}
