{
  "type": "record",
  "name": "Envelope",
  "namespace": "reeledlegacy.public.post",
  "fields": [
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Value",
          "fields": [
            {
              "name": "id",
              "type": "long"
            },
            {
              "name": "author_id",
              "type": "long"
            },
            {
              "name": "category_id",
              "type": "long"
            },
            {
              "name": "description",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "duration",
              "type": "long"
            },
            {
              "name": "is_monetized",
              "type": "boolean"
            },
            {
              "name": "title",
              "type": "string"
            },
            {
              "name": "video_url",
              "type": "string"
            },
            {
              "name": "version",
              "type": "long"
            }
          ],
          "connect.name": "reeledlegacy.public.post.Value"
        }
      ]
    },
    {
      "name": "after",
      "type": [
        "null",
        "Value"
      ]
    },
    {
      "name": "source",
      "type": {
        "type": "record",
        "name": "Source",
        "namespace": "io.debezium.connector.postgresql",
        "fields": [
          {
            "name": "version",
            "type": "string"
          },
          {
            "name": "connector",
            "type": "string"
          },
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "ts_ms",
            "type": "long"
          },
          {
            "name": "snapshot",
            "type": [
              {
                "type": "string",
                "connect.version": 1,
                "connect.parameters": {
                  "allowed": "true,last,false"
                },
                "connect.default": "false",
                "connect.name": "io.debezium.data.Enum"
              },
              "null"
            ],
            "default": "false"
          },
          {
            "name": "db",
            "type": "string"
          },
          {
            "name": "schema",
            "type": "string"
          },
          {
            "name": "table",
            "type": "string"
          },
          {
            "name": "txId",
            "type": [
              "null",
              "long"
            ]
          },
          {
            "name": "lsn",
            "type": [
              "null",
              "long"
            ]
          },
          {
            "name": "xmin",
            "type": [
              "null",
              "long"
            ]
          }
        ],
        "connect.name": "io.debezium.connector.postgresql.Source"
      }
    },
    {
      "name": "op",
      "type": "string"
    },
    {
      "name": "ts_ms",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "name": "transaction",
      "type": [
        "null",
        {
          "type": "record",
          "name": "ConnectDefault",
          "namespace": "io.confluent.connect.avro",
          "fields": [
            {
              "name": "id",
              "type": "string"
            },
            {
              "name": "total_order",
              "type": "long"
            },
            {
              "name": "data_collection_order",
              "type": "long"
            }
          ]
        }
      ]
    }
  ],
  "connect.name": "reeledlegacy.public.post.Envelope"
}
